# Generated by Django 5.2 on 2025-04-23 19:XX
# filepath: c:\python\django\pagina\app1\migrations\000X_unique_email_constraint.py

from django.db import migrations, models

# --- IMPORTANTE: Ajusta el nombre de la tabla si es diferente ---
# Por defecto, Django usa 'auth_user' para el modelo User estándar.
USER_TABLE_NAME = 'auth_user'
# ---------------------------------------------------------------

class Migration(migrations.Migration):

    # --- Asegúrate de que 'dependencies' apunte a tu última migración de 'app1' ---
    dependencies = [
        ('app1', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]
    # --------------------------------------------------------------------------

    operations = [
        # --- MODIFICACIÓN PARA SQLITE ---
        # Añade un ÍNDICE ÚNICO al campo 'email' en lugar de una CONSTRAINT
        migrations.RunSQL(
            # Crea un índice único llamado 'unique_user_email_idx' en la columna 'email'
            sql=f"CREATE UNIQUE INDEX unique_user_email_idx ON {USER_TABLE_NAME} (email);",
            # Elimina el índice si se revierte la migración
            reverse_sql=f"DROP INDEX unique_user_email_idx;",
        ),
        # ---------------------------------
    ]
